/**
 * Registre des types de cartes du dashboard — libellé, description, icône,
 * taille par défaut et périodes supportées. Toutes les cartes s'appuient sur
 * des endpoints réels (aucune donnée fabriquée).
 */
import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlertTriangle,
  CalendarRange,
  CheckCircle2,
  CircleDot,
  Flame,
  HeartPulse,
  Sparkles,
  TrendingDown,
} from "lucide-react";
import type { DashboardCard, DashboardCardSize } from "@/lib/api/dashboard-card-service";

// ---------------------------------------------------------------------------
// Période globale de la section Analytics
// ---------------------------------------------------------------------------

/** Période GLOBALE — préférence UI (localStorage par workspace), pas une donnée métier. */
export type GlobalRange = "24h" | "7d" | "30d";

export const GLOBAL_RANGES: readonly { value: GlobalRange; label: string }[] = [
  { value: "24h", label: "24h" },
  { value: "7d", label: "7d" },
  { value: "30d", label: "30d" },
];

/** Fenêtre en jours de la période globale (pour les cartes qui savent l'honorer). */
export const GLOBAL_RANGE_DAYS: Record<GlobalRange, number> = { "24h": 1, "7d": 7, "30d": 30 };

export const rangeStorageKey = (slug: string) => `tf-dashboard-range:${slug}`;

// ---------------------------------------------------------------------------
// Définitions des cartes
// ---------------------------------------------------------------------------

export interface CardTimeRangeOption {
  value: string;
  label: string;
}

export interface CardDefinition {
  type: string;
  label: string;
  description: string;
  icon: LucideIcon;
  defaultSize: DashboardCardSize;
  /** Périodes propres à la carte (sous-menu « Période ») — absent si la carte n'a pas de fenêtre. */
  timeRanges?: readonly CardTimeRangeOption[];
  /** true = absente de la grille « Ajouter » (ex. ai-chart, créée via la génération IA). */
  hiddenInPicker?: boolean;
}

export const CARD_DEFINITIONS: readonly CardDefinition[] = [
  {
    type: "ops-health",
    label: "Operations health",
    description: "Breakdown of healthy / at-risk / critical / paused operations.",
    icon: HeartPulse,
    defaultSize: "1",
  },
  {
    type: "throughput",
    label: "Throughput",
    description: "Tasks resolved over time, from your real data.",
    icon: Activity,
    defaultSize: "2",
    timeRanges: [
      { value: "30d", label: "30 days (daily)" },
      { value: "8w", label: "8 weeks (weekly)" },
    ],
  },
  {
    type: "needs-attention",
    label: "Needs attention",
    description: "At-risk or critical operations that need action.",
    icon: AlertTriangle,
    defaultSize: "1",
  },
  {
    type: "ai-usage",
    label: "Cortex usage",
    description: "Monthly token usage vs plan cap.",
    icon: Sparkles,
    defaultSize: "1",
  },
  {
    type: "kpi-resolved",
    label: "Resolved tasks",
    description: "Total resolved this month, with the delta vs last month.",
    icon: CheckCircle2,
    defaultSize: "1",
  },
  {
    type: "kpi-velocity",
    label: "Velocity",
    description: "Issues delivered over the last 7 days.",
    icon: Flame,
    defaultSize: "1",
  },
  {
    type: "kpi-open",
    label: "Open issues",
    description: "Work in progress, across all operations.",
    icon: CircleDot,
    defaultSize: "1",
  },
  {
    type: "burndown",
    label: "Burndown",
    description: "Remaining vs the sprint's ideal trajectory.",
    icon: TrendingDown,
    defaultSize: "2",
  },
  {
    type: "workload",
    label: "Team workload",
    description: "Member × day heatmap of assigned due dates.",
    icon: CalendarRange,
    defaultSize: "2",
    timeRanges: [
      { value: "7d", label: "7 days" },
      { value: "14d", label: "14 days" },
      { value: "30d", label: "30 days" },
    ],
  },
  {
    type: "ai-chart",
    label: "AI chart",
    description: "Chart generated by Cortex from your real data.",
    icon: Sparkles,
    defaultSize: "2",
    hiddenInPicker: true,
  },
];

export const CARD_REGISTRY: Readonly<Record<string, CardDefinition>> = Object.fromEntries(
  CARD_DEFINITIONS.map((d) => [d.type, d]),
);

/** Titre affiché d'une carte : titre custom, sinon libellé du registre, sinon le type brut. */
export function cardTitle(card: DashboardCard): string {
  return card.title ?? CARD_REGISTRY[card.cardType]?.label ?? card.cardType;
}

// ---------------------------------------------------------------------------
// Props communes des corps de carte
// ---------------------------------------------------------------------------

export interface DashboardCardBodyProps {
  slug: string;
  card: DashboardCard;
  /** Période globale de la section — fenêtre par défaut, le réglage par carte prime. */
  globalRange: GlobalRange;
  /** Incrémenté par le refresh global et le « Actualiser » de la carte. */
  refreshToken: number;
}
