// Traductions françaises pour TaskForce AI

import type { TranslationKeys } from "./constants_en";

export const CONSTANTS_FR: TranslationKeys = {
  // Commun
  common: {
    appName: "Taskforce",
    language: "Langue",
    theme: "Thème",
    light: "Clair",
    dark: "Sombre",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    cancel: "Annuler",
    confirm: "Confirmer",
    close: "Fermer",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    back: "Retour",
    next: "Suivant",
    previous: "Précédent",
    finish: "Terminer",
    or: "ou",
    search: "Rechercher...",
    notifications: "Notifications",
    logout: "Se déconnecter",
    noResults: "Aucun résultat trouvé",
    viewAll: "Tout afficher",
    createNew: "Créer",
    filter: "Filtrer",
    sort: "Trier par",
    export: "Exporter",
    required: "Requis",
    optional: "Optionnel",
    comingSoon: "Bientôt disponible",
    free: "Gratuit",
    pro: "Pro",
    enterprise: "Entreprise",
    upgrade: "Mettre à niveau",
    learnMore: "En savoir plus",
  },

  // Authentification - Connexion
  auth: {
    login: {
      title: "Bon retour",
      subtitle: "Connectez-vous à votre compte pour continuer",
      emailLabel: "Adresse email",
      emailPlaceholder: "Entrez votre email",
      passwordLabel: "Mot de passe",
      passwordPlaceholder: "Entrez votre mot de passe",
      rememberMe: "Se souvenir de moi",
      forgotPassword: "Mot de passe oublié ?",
      signInButton: "Se connecter",
      noAccount: "Pas encore de compte ?",
      signUpLink: "S'inscrire",
      signInWithGoogle: "Continuer avec Google",
      signInWithGithub: "Continuer avec GitHub",
      dividerText: "Ou continuer avec",
    },

    // Authentification - Inscription
    register: {
      title: "Créez votre compte",
      subtitle: "Commencez votre essai gratuit dès aujourd'hui",
      alreadyHaveAccount: "Vous avez déjà un compte ?",
      signInLink: "Se connecter",
      
      // Étape 1 : Informations personnelles
      step1: {
        title: "Informations personnelles",
        subtitle: "Commençons par vos informations de base",
        firstNameLabel: "Prénom",
        firstNamePlaceholder: "Entrez votre prénom",
        lastNameLabel: "Nom",
        lastNamePlaceholder: "Entrez votre nom",
        emailLabel: "Adresse email",
        emailPlaceholder: "Entrez votre email",
        passwordLabel: "Mot de passe",
        passwordPlaceholder: "Créez un mot de passe",
        confirmPasswordLabel: "Confirmez le mot de passe",
        confirmPasswordPlaceholder: "Confirmez votre mot de passe",
        acceptTerms: "J'accepte les",
        termsLink: "Conditions d'utilisation",
        and: "et la",
        privacyLink: "Politique de confidentialité",
      },

      // Étape 2 : Organisation
      step2: {
        title: "Détails de l'organisation",
        subtitle: "Parlez-nous de votre organisation",
        organizationNameLabel: "Nom de l'organisation",
        organizationNamePlaceholder: "Entrez le nom de votre organisation",
        roleLabel: "Votre rôle",
        rolePlaceholder: "Sélectionnez votre rôle",
        teamSizeLabel: "Taille de l'équipe",
        teamSizePlaceholder: "Sélectionnez la taille de l'équipe",
        industryLabel: "Secteur d'activité",
        industryPlaceholder: "Sélectionnez votre secteur",
        
        roles: {
          owner: "Propriétaire",
          admin: "Administrateur",
          manager: "Manager",
          member: "Membre de l'équipe",
          other: "Autre",
        },
        
        teamSizes: {
          solo: "Juste moi",
          small: "2-10 personnes",
          medium: "11-50 personnes",
          large: "51-200 personnes",
          enterprise: "200+ personnes",
        },
        
        industries: {
          technology: "Technologie",
          finance: "Finance",
          healthcare: "Santé",
          education: "Éducation",
          retail: "Commerce",
          manufacturing: "Industrie",
          other: "Autre",
        },
      },

      // Étape 3 : Confirmation
      step3: {
        title: "Tout est prêt !",
        subtitle: "Vérifiez vos informations et commencez votre essai gratuit",
        reviewTitle: "Vérifiez vos informations",
        personalInfo: "Informations personnelles",
        organizationInfo: "Organisation",
        freeTrialTitle: "Essai gratuit inclus",
        freeTrialDescription: "Commencez avec un essai gratuit de 14 jours. Aucune carte bancaire requise.",
        createAccountButton: "Créer le compte",
        startTrialButton: "Commencer l'essai gratuit",
      },

      // Indicateur de progression
      progress: {
        step1: "Personnel",
        step2: "Organisation",
        step3: "Confirmer",
      },
    },

    // Réinitialisation du mot de passe
    passwordReset: {
      title: "Réinitialisez votre mot de passe",
      subtitle: "Entrez votre email pour recevoir un lien de réinitialisation",
      emailLabel: "Adresse email",
      emailPlaceholder: "Entrez votre email",
      sendLinkButton: "Envoyer le lien",
      backToLogin: "Retour à la connexion",
      checkEmail: "Vérifiez vos emails",
      checkEmailDescription: "Nous avons envoyé un lien de réinitialisation à votre adresse email.",
    },

    // Erreurs
    errors: {
      invalidEmail: "Veuillez entrer une adresse email valide",
      emailRequired: "L'email est requis",
      passwordRequired: "Le mot de passe est requis",
      passwordTooShort: "Le mot de passe doit contenir au moins 8 caractères",
      passwordsDoNotMatch: "Les mots de passe ne correspondent pas",
      firstNameRequired: "Le prénom est requis",
      lastNameRequired: "Le nom est requis",
      organizationRequired: "Le nom de l'organisation est requis",
      roleRequired: "Le rôle est requis",
      termsRequired: "Vous devez accepter les conditions d'utilisation",
      loginFailed: "Email ou mot de passe incorrect",
      registrationFailed: "L'inscription a échoué. Veuillez réessayer.",
      networkError: "Erreur réseau. Veuillez vérifier votre connexion.",
      unexpectedError: "Une erreur inattendue s'est produite. Veuillez réessayer.",
      emailAlreadyExists: "Cet email est déjà enregistré",
    },

    // Messages de succès
    success: {
      loginSuccess: "Connexion réussie !",
      registrationSuccess: "Compte créé avec succès !",
      passwordResetSent: "Lien de réinitialisation envoyé à votre email",
      emailVerified: "Email vérifié avec succès",
    },

    // Écrans d'authentification redessinés — routés depuis les composants d'auth. Les jetons
    // {provider} / {email} / {seconds} sont substitués dans le composant via String.replace.
    ui: {
      // Commun
      email: "Email",
      emailPlaceholder: "vous@entreprise.com",
      password: "Mot de passe",
      signIn: "Se connecter",
      signingIn: "Connexion…",
      createAccount: "Créer un compte",
      noAccount: "Pas encore de compte ?",
      alreadyHaveAccount: "Vous avez déjà un compte ?",
      backToSite: "Retour au site",
      // Connexion
      loginTitle: "Connexion",
      loginSubtitle: "Accédez à votre espace de travail.",
      forgotPassword: "Mot de passe oublié ?",
      tooManyAttempts: "Trop de tentatives. Réessayez dans {seconds} secondes",
      // Inscription (étape 1)
      registerTitle: "Créer votre compte",
      firstName: "Prénom",
      lastName: "Nom",
      confirm: "Confirmer",
      strengthStrong: "Robuste",
      strengthFair: "Correct",
      strengthWeak: "Trop faible",
      notRobot: "Je confirme ne pas être un robot",
      acceptPrefix: "J'accepte les",
      termsLink: "conditions",
      acceptSeparator: "et la",
      privacyLink: "politique de confidentialité",
      continue: "Continuer",
      oneMoment: "Un instant…",
      confirmNotRobot: "Veuillez confirmer que vous n'êtes pas un robot",
      completeVerification: "Veuillez compléter la vérification anti-robot",
      // Réinitialisation du mot de passe
      forgotTitle: "Mot de passe oublié",
      forgotSubtitle: "Indiquez votre adresse, nous vous envoyons un code de vérification.",
      sendCode: "Envoyer le code",
      sending: "Envoi en cours…",
      codeSentTitle: "Code envoyé !",
      codeSentSubtitle: "Saisissez le code à 6 chiffres reçu à l'adresse {email}, puis choisissez un nouveau mot de passe.",
      verificationCode: "Code de vérification",
      newPassword: "Nouveau mot de passe",
      confirmPassword: "Confirmer le mot de passe",
      resetPassword: "Réinitialiser le mot de passe",
      resetting: "Réinitialisation…",
      codeNotReceived: "Code non reçu ?",
      resend: "Renvoyer",
      backToLogin: "Retour à la connexion",
      enterEmail: "Veuillez entrer votre adresse email",
      toastCodeSentTitle: "Code envoyé",
      toastCodeSentDesc: "Vérifiez votre boîte de réception",
      sendEmailError: "Erreur lors de l'envoi de l'email",
      fillAllFields: "Veuillez remplir tous les champs",
      otpSixDigits: "Le code OTP doit contenir 6 chiffres",
      resetSuccessTitle: "Mot de passe réinitialisé",
      resetSuccessDesc: "Vous pouvez maintenant vous connecter",
      resetError: "Erreur lors de la réinitialisation",
      codeResentTitle: "Code renvoyé",
      codeResentDesc: "Un nouveau code a été envoyé à votre adresse email",
      resendError: "Erreur lors du renvoi du code",
      // Boutons sociaux
      socialComingSoonTitle: "Connexion {provider} bientôt disponible",
      socialComingSoonDescription: "En attendant, utilisez votre adresse et votre mot de passe.",
      socialUnavailableTitle: "Connexion {provider} indisponible",
      socialComingSoonBadge: "bientôt disponible",
      // Rappel OAuth
      callbackInProgressTitle: "Connexion en cours",
      callbackInProgressSubtitle: "Un instant, nous finalisons votre session.",
      callbackFailedTitle: "Connexion impossible",
      callbackIncomplete: "Réponse incomplète du fournisseur d'identité.",
      callbackConnectFailed: "Connexion impossible.",
      callbackBackToLogin: "Revenir à la connexion",
      // Fil d'étapes (inscription)
      stepAccount: "Compte",
      stepVerification: "Vérification",
      stepAria: "Étape {current} sur {total} : {label}",
      // Vérification d'inscription (OTP)
      verifyTitle: "Code de vérification",
      verifySentTo: "Code envoyé à {email}",
      verifyOtpHint: "Entrez le code à 6 chiffres envoyé par email.",
      verifyButton: "Vérifier",
      verifying: "Vérification…",
      verifyNotReceived: "Vous n'avez pas reçu le code ?",
      resendCode: "Renvoyer le code",
      resendIn: "Renvoyer le code dans {seconds}s",
      sendingShort: "Envoi...",
      backToRegister: "Revenir à l'inscription",
      verifySessionExpired: "Session expirée ou données incomplètes",
      verifySessionExpiredDesc: "Veuillez recommencer le processus d'inscription",
      verifyCodeSentTitle: "Code de vérification envoyé",
      verifyCodeSentDesc: "Consultez votre boîte mail",
      verifyRegisterError: "Erreur lors de l'inscription",
      verifyResendWait: "Veuillez attendre {seconds} secondes avant de renvoyer le code",
      verifyCodeResent: "Code de vérification renvoyé",
      verifySendError: "Erreur lors de l'envoi du code",
      verifyInvalidCode6: "Veuillez entrer un code à 6 chiffres valide",
      verifyRedirectPayment: "Redirection vers la page de paiement...",
      verifyRedirectPaymentDesc: "Finalisation de votre abonnement",
      verifySuccessTitle: "Compte vérifié avec succès !",
      verifySuccessDesc: "Connectez-vous pour accéder à votre espace.",
      verifyInvalidCode: "Code de vérification invalide",
    },
  },

  // Accessibilité
  accessibility: {
    toggleTheme: "Changer de thème",
    changeLanguage: "Changer de langue",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    skipToContent: "Aller au contenu principal",
  },

  // Navigation (sidebar)
  nav: {
    dashboard: "Dashboard",
    myWork: "Ma file",
    inbox: "Signaux",
    projects: "Opérations",
    issues: "Tâches",
    cycles: "Sprints",
    roadmap: "Feuille de route",
    teams: "Équipes",
    members: "Membres",
    skills: "Compétences",
    analytics: "Intelligence",
    agents: "Agents",
    brain: "Brain OS",
    messages: "Messages",
    discussions: "Discussions",
    settings: "Paramètres",
    help: "Aide",
    createProject: "Nouveau projet",
    comingSoon: "Bientôt",
    sub: {
      myAll: "Toutes mes files",
      myIssues: "Tâches",
      myCycles: "Sprints",
      myPages: "Pages",
      allNotifications: "Tous les signaux",
      mentions: "Mentions",
      alerts: "Alertes",
      assignments: "Assigné à moi",
    },
  },

  // Page Dashboard
  dashboard: {
    title: "Tableau de bord",
    welcomeBack: "Bon retour",
    stats: {
      activeProjects: "Projets actifs",
      openIssues: "Tâches ouvertes",
      myTasks: "Mes tâches",
      teamMembers: "Membres",
      completedThisWeek: "Terminées cette semaine",
      overloaded: "En surcharge",
    },
    activity: {
      title: "Activité récente",
      empty: "Aucune activité récente",
      viewAll: "Voir toute l'activité",
    },
    quickActions: {
      title: "Actions rapides",
      createProject: "Nouveau projet",
      createIssue: "Nouvelle tâche",
      inviteMember: "Inviter un membre",
    },
    workload: {
      title: "Charge de l'équipe",
      noData: "Aucune donnée de charge disponible",
      overloaded: "En surcharge",
      available: "Disponible",
      capacity: "capacité",
    },
  },

  // Page Projets
  projects: {
    title: "Projets",
    subtitle: "Tous les projets de votre espace de travail",
    newProject: "Nouveau projet",
    searchPlaceholder: "Rechercher des projets...",
    empty: {
      title: "Aucun projet",
      description: "Créez votre premier projet pour commencer",
      cta: "Créer un projet",
    },
    emptySearch: "Aucun projet ne correspond à votre recherche",
    status: {
      active: "Actif",
      archived: "Archivé",
      paused: "En pause",
    },
    meta: {
      issues: "tâches",
      members: "membres",
      updatedAt: "Mis à jour",
      progress: "Progression",
    },
    filters: {
      all: "Tous",
      active: "Actifs",
      archived: "Archivés",
    },
    detail: {
      board: "Tableau",
      list: "Liste",
      backlog: "Backlog",
      issues: "Tâches",
      cycles: "Cycles",
      roadmap: "Roadmap",
      pages: "Pages",
      members: "Membres",
      teams: "Équipes",
      settings: "Paramètres",
      newIssue: "Nouvelle tâche",
      noIssues: "Aucune tâche dans cette colonne",
      addIssue: "Ajouter une tâche",
    },
  },

  // Page My Work
  myWork: {
    title: "Mon travail",
    subtitle: "Vos tâches, cycles et pages assignés",
    tabs: {
      issues: "Mes tâches",
      cycles: "Mes cycles",
      pages: "Mes pages",
    },
    empty: {
      issues: "Aucune tâche assignée",
      cycles: "Vous ne faites partie d'aucun cycle actif",
      pages: "Vous n'avez pas encore créé de pages",
      description: "Les nouveaux éléments apparaîtront ici une fois assignés",
    },
    issues: {
      priority: "Priorité",
      status: "Statut",
      dueDate: "Échéance",
      project: "Projet",
      noDue: "Pas d'échéance",
    },
    cycles: {
      active: "Actif",
      upcoming: "À venir",
      completed: "Terminé",
      progress: "Progression",
      issues: "tâches",
      endsIn: "Se termine dans",
      startedAgo: "Démarré",
    },
    pages: {
      lastEdited: "Dernière modification",
      by: "par",
      viewPage: "Voir la page",
    },
  },

  // Page Inbox
  inbox: {
    title: "Boîte de réception",
    subtitle: "Restez à jour sur vos notifications",
    tabs: {
      all: "Tout",
      mentions: "Mentions",
      alerts: "Alertes",
      assignments: "Assignations",
    },
    empty: {
      all: "Tout est à jour !",
      mentions: "Aucune mention pour l'instant",
      alerts: "Aucune alerte",
      assignments: "Aucune assignation",
      description: "Les nouvelles notifications apparaîtront ici",
    },
    markAllRead: "Tout marquer comme lu",
    markRead: "Marquer comme lu",
    unread: "Non lu",
    types: {
      mention: "vous a mentionné",
      assigned: "vous a assigné à",
      commented: "a commenté",
      statusChanged: "a changé le statut de",
      dueSoon: "Échéance proche",
      overdue: "En retard",
      completed: "a terminé",
    },
  },

  analytics: {
    title: "Analytiques",
    subtitle: "Suivez les performances de votre équipe et la santé des projets.",
    upgradeTitle: "Débloquer les analytiques",
    upgradeDesc: "Les graphiques détaillés, le suivi de vélocité et les insights de charge d'équipe sont disponibles sur le plan Pro.",
    overview: "Vue d'ensemble",
    velocity: "Vélocité",
    workload: "Charge d'équipe",
    progress: "Avancement des projets",
    issuesCreated: "Issues créées",
    issuesCompleted: "Issues terminées",
    cyclesCompleted: "Cycles terminés",
    activeProjects: "Projets actifs",
    thisMonth: "ce mois-ci",
    vsLastMonth: "vs mois dernier",
    completionRate: "Taux de complétion",
    avgCycleTime: "Durée moy. de cycle",
    days: "jours",
  },

  settings: {
    title: "Paramètres",
    profile: "Profil",
    account: "Compte",
    notifications: "Notifications",
    billing: "Facturation",
    team: "Équipe",
    displayName: "Nom d'affichage",
    email: "Email",
    language: "Langue",
    theme: "Thème",
    currentPlan: "Plan actuel",
    upgrade: "Changer de plan",
    dangerZone: "Zone dangereuse",
    deleteAccount: "Supprimer le compte",
    deleteAccountDesc: "Supprimer définitivement votre compte et toutes les données. Cette action est irréversible.",
    saveChanges: "Enregistrer",
    saved: "Enregistré !",
  },

  help: {
    title: "Aide & Docs",
    subtitle: "Trouvez des réponses, guides et ressources.",
    searchPlaceholder: "Rechercher dans la doc, guides, FAQ…",
    categories: "Catégories",
    gettingStarted: "Débuter",
    gettingStartedDesc: "Configurez votre espace, invitez votre équipe, créez votre premier projet.",
    projects: "Projets & Issues",
    projectsDesc: "Organisez le travail avec des projets, issues, cycles et backlogs.",
    integrations: "Intégrations",
    integrationsDesc: "Connectez Taskforce avec GitHub, Slack, Jira et plus.",
    security: "Sécurité & Permissions",
    securityDesc: "Gérez les rôles, SSO, journaux d'audit et politiques de rétention.",
    billing: "Facturation & Plans",
    billingDesc: "Comprenez votre plan, gérez les abonnements et consultez les factures.",
    contactSupport: "Contacter le support",
    contactSupportDesc: "Vous ne trouvez pas ce que vous cherchez ? Notre équipe est là pour vous aider.",
    openChat: "Ouvrir le chat",
    sendEmail: "Envoyer un email",
    popularArticles: "Articles populaires",
    articles: {
      a1: "Comment créer ma première issue",
      a2: "Configurer des cycles et sprints",
      a3: "Utiliser le tableau kanban",
      a4: "Inviter des membres d'équipe",
      a5: "Configurer les notifications",
    },
  },

  // Coquille de l'app — footer, barre supérieure, sélecteur d'espace (sur chaque écran authentifié).
  shell: {
    // Footer
    privacy: "Confidentialité",
    legalNotices: "Mentions légales",
    // Barre supérieure
    search: "Rechercher…",
    searchAria: "Rechercher",
    openCommandPalette: "Ouvrir la palette de commandes",
    askAi: "Demander à l'IA",
    openAiAssistant: "Ouvrir l'assistant IA",
    aiProFeature: "L'assistant IA est une fonctionnalité Pro. Passez à Pro pour l'activer.",
    experimental: "Expérimentation",
    giveFeedback: "Donner mon feedback",
    // Sélecteur d'espace de travail
    workspaces: "Espaces de travail",
    yourWorkspaces: "Vos espaces",
    sharedWorkspaces: "Partagés avec vous",
    active: "actif",
    workspacesCount: "{count}/{limit} espaces",
    limitReachedUpgrade: "Limite atteinte — Améliorer",
    newWorkspace: "Nouveau workspace",
    createWorkspace: "Créer un workspace",
    workspaceName: "Nom du workspace",
    workspaceNamePlaceholder: "Mon équipe",
    brainTemplate: "Brain OS — gabarit de départ",
    templateBlank: "Vierge (16 domaines)",
    templateSaas: "SaaS (expert)",
    templateEcommerce: "E-commerce (expert)",
    templateMarketplace: "Marketplace (expert)",
    templateAgentic: "Produit agentique (expert)",
    templateHint: "Pré-remplit la mémoire de connaissance (ADR, SOP, décisions…) selon ton activité.",
    creating: "Création…",
  },
} as const
